### ISSUE TITLE
Add Neural Internet

### ISSUE THREAD

**Issue by asifehmad** [opentensor/bittensor-delegates#8]
Hi, Please add Neural Internet details as:

{'5HNQURvmjjYhTSksi8Wfsw676b4owGwfLR2BFAQzG7H3HhYf': 
{'name': 'Neural Internet', 
'url': 'www.neuralinternet.ai', 
'description': 'An AI research and development Decentralized Autonomous Organization (DAO)', 
'signature': '5e617c1626d4825cd0c11769e31fe4dda611cebd8a4d46f533886ad057072e2a58e0ecef2805139f2b43ea8d51023f7db878ad45cd3f8fba45ab01223da3488e'}}

**Comment by joeylegere** [comment]
Hi, can you please submit this as a PR and not as an issue? It will be approved and merged as soon as it passes the checks. Thanks!
